### ISSUE TITLE
basic & minimum unit testing coverage

### ISSUE THREAD

**Issue by nykevinwong** [Flaxis/slick-ui#10]
can we have some minimum unit testing code provided so that any broken change can be detected when a new change is introduced?  is it possible to do so for game UI library?

**Comment by Flaxis** [comment]
Adding unit tests is possible, but I think having the preview files kind of makes that unnecessary, because a lot more code can be covered by those than a unit test can do. As long as preview files keep being added for every feature that is introduced, we should be safe.
Though if you can set something up that's more reliable or easier to test, I'd be very curious!
