### ISSUE TITLE
Update button/element text and/or destroy panel?

### ISSUE THREAD

**Issue by praine** [Flaxis/slick-ui#16]
Hi there, thanks for this useful plugin. I'm trying to use it to dynamically generate multiple choice questions (see image). I either need to destroy the panel and create a new one each time a new question prompt occurs, or update the text on the buttons/elements.

I can't find anything in the documentation to destroy() or kill() panels once they have been created, nor any way to dynamically update button/element text.

Any help gratefully received.

Best,
Paul
![screen shot 2017-01-31 at 3 29 05 pm](https://cloud.githubusercontent.com/assets/6300133/22454560/0aa612b6-e7ca-11e6-9a8d-fbad4c30e59f.png)

**Comment by Flaxis** [comment]
There isn't really any documentation for changing text. There should be a multi paged documentation at some point.

Anyway, you can change a TextElement's value like so:
```javascript
yourTextElement.text.text = 'My updated text.';
```

I would advise against destroying and re-creating panels, since it tends to go against object oriented design principles. A panel / button / text / anything should have one purpose and one purpose only. If you're using the same panel for multiple views, you might be doing something wrong.

**Comment by praine** [comment]
Thanks for your prompt reply, Flaxis. I'll try updating the text with the method you provided.

**Comment by Flaxis** [comment]
I just noticed as well, that you should be able to use `textElement.value = 'foo';`, since I apparently made a setter for it :)
Anyway, is this issue solved?

**Comment by praine** [comment]
Thanks for that! Closing the issue now..
