### ISSUE TITLE
Resize and repositioning elements

### ISSUE THREAD

**Issue by giorgiobeggiora** [Flaxis/slick-ui#3]
Hi,

i'm developing a responsive application. How can i manage the responsiveness of the elements? I need to resize and repoisition them on resize.

Thanks

**Comment by shinyvision** [comment]
You _can_ change the width and height of panels, buttons, etc. but should be avoided if possible. Changing the width or height of an element can be done by setting the property of the same name. Don't do this in a window resize event, since a lot of processing is used to resize elements.

This issue will be closed because it doesn't address any code issues. If you have additional questions, feel free to ask them [here](http://phaser.io/news/2016/08/slickui), [here](http://www.html5gamedevs.com/topic/24215-slickui-ui-manager-for-phaser-games/) or [here](https://gitter.im/slick-ui/Lobby) :)

**Comment by Flaxis** [comment]
And I used the wrong user to do stuff again... Lol
