### ISSUE TITLE
TextField listen keyboard

### ISSUE THREAD

**Issue by MonTty** [Flaxis/slick-ui#9]
the textfield can listen the keyboard??

**Comment by Flaxis** [comment]
Not at the moment. However, you can put this functionality in the library or even in your game by using the events the virtual keyboard dispatches.

I'm not sure if adding listeners to the virtual keyboard keys would be a good idea, because we don't want them to conflict with other event listeners that might be on the same keys.
If you can come up with something that works and doesn't risk messing up a game's keyboard event system, feel free to suggest something or add a PR.
